### ISSUE TITLE
Zwangerschap.type

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#10]
In het formulier III C moet je aangeven of een persoon zwanger geweest is (ja, nee, onbekend). In geval van onbekend, geven we dit aan door een type “OnbekendePersoonsgebeurtenis”.In het formulier staat ook “zwanger geweest in het jaar voor het overlijden”. Deze specifieke tijdsindicatie is niet duidelijk te modelleren.

**Comment by jitsedc** [comment]
Voor Bevalling is dit ook het geval.

**Comment by jitsedc** [comment]
Toevoeging status attribuut op beide met suggestie voor codelijst op het UML diagram.

**Comment by tdekeyser** [comment]
in orde, mag gesloten worden
