### ISSUE TITLE
Zwangerschap.transfer - generiek maken Zorg - Procedure

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#13]
In het formulier staat of er een transfer is geweest tijdens de zwangerschap (ja, nee, onbekend). Wat is dit, en hoe kunnen we dit modelleren?

**Comment by jitsedc** [comment]
Het attribuut Geboortetoestand.zorg werd generiek gemaakt en op Gezondheidstoestand geplaatst. De verwachte waarde is [FHIR:Procedure ](https://hl7.org/fhir/procedure.html) met een aanzet tot codering die nodig is voor de use cases in het UML diagram.

**Comment by tdekeyser** [comment]
is in orde -- mag gesloten worden
