### ISSUE TITLE
BezwaarType

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#15]
- Waarom bestaan zowel ‘verplichteOnmiddellijkeKisting’ en ‘verplichteOnmiddellijkeKistingHermetisch’?
- Op formulier enkel de laatste optie beschikbaar.
- VerplichteOnmiddelijkeKisting is ook niet echt een bezwaar maar eerder een verplichting. Risico en bezwaar zijn uit elkaar getrokken. Waarom is verplichting er dan ook niet uitgetrokken?

**Comment by jitsedc** [comment]
- verplichteOnmiddellijkeKisting werd verwijderd uit de enumeratie. verplichteOnmiddellijkeKistingHermetisch werd toegevoegd aan nieuw attribuut 'maatregel' om de logica door te trekken van risico > bezwaar > maatregel.

**Comment by tdekeyser** [comment]
In orde - mag gesloten worden
