### ISSUE TITLE
Ongeval moet in scope genomen worden

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#2]
Ongeval moet toch in scope genomen worden voor verwerking van overlijdens. Kunlabora komt met voorstel.

**Comment by tdekeyser** [comment]
Voorstel voor het toevoegen van Ongeval aan OverlijdensToestand.

<img width="644" alt="image" src="https://github.com/Informatievlaanderen/OSLOthema-overlijdensaangifte/assets/12743692/5a52a632-a4f5-4071-97d1-a5c0a8530e7b">

**Comment by jitsedc** [comment]
Dag Tom

Bedankt voor de input. Ik stel voor om het iets anders op te lossen:

De Overlijdenstoestand > veroorzaaktDoorOngeval > Ongeval met daarop een locatie. Het verwachte datatype is dan Locatie waarop we een typering kunnen zetten met als verwachte waarde PlaatsOngevalCode. Indien het een andereLocatie moet zijn zou ik gewoon de codelijst substitueren door een TaalString. 

![image](https://github.com/Informatievlaanderen/OSLOthema-overlijdensaangifte/assets/93584054/3d924adf-1a3b-4073-baea-5d6dcab8b4ab)


Momenteel was de AardOverlijden zo samengesteld. Heb je liever dat dit overeenkomt met wat jij hebt voorgesteld in je enum?

![image](https://github.com/Informatievlaanderen/OSLOthema-overlijdensaangifte/assets/93584054/07d14add-fc43-442d-b0ad-25255636ed30)

Goed zo? Dan pas ik aan.

Merci!

**Comment by tdekeyser** [comment]
Ik zie net dat er nog een string veld "omstandigheden" ook op Ongeval moet komen. Is ondertussen toegevoegd en mag gesloten worden
