### ISSUE TITLE
Persoonsgebeurtenis.plaats en Persoonsgebeurtenis.locatie

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#4]
Voor een overlijden is er zowel een locatie nodig (ziekenhuis, thuis, …) als een adres voorstelling (thuis op de xxx straat ).

**Comment by jitsedc** [comment]
Usage note werd aangepast naar: 

> Binnen de context van OSLO-Overlijdensaangifte is dit attribuut te gebruiken om de plaats of concreet adres van de plaats van overlijden weer te geven. Het adres mag ook weergegeven worden als een Adresvoorstelling. Voor de Verblijfplaats en Domicilie van een Persoon dienen de respectievelijke klassen uit OSLO-Persoon gebruikt te worden.

Kardinaliteit voor Persoonsgebeurtenis.plaats werd ook opengesteld naar 0..* zodat het mogelijk wordt om beide tegelijk mee te geven.

**Comment by tdekeyser** [comment]
is in orde -- mag gesloten worden
