### ISSUE TITLE
Feedback Doodsoorzaak

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#6]
- Doodsoorzaak.duur | Veld “duur” ontbreekt op doodsoorzaak. Dit moet een Periode zijn (waarde + eenheidcode) zonder begin- en einddatum.
- Doodsoorzaak.volgtOp | Geen lijst nodig. Cardinaliteit 0..1.
- Doodsoorzaak.geassocieerdeOorzaak | Cardinaliteit veranderen naar 0..1. Een geassocieerde oorzaak moet ook een duur ondersteunen.
- Doodsoorzaak.geassocieerdeOorzaak | Geassocieerde oorzaken zijn conceptueel anders dan de doodsoorzaken. Het zou best ook als apart veld beschouwd worden voor de duidelijkheid.
- Doodsoorzaak.relatie? | Model III D maakt het mogelijk om een doodsoorzaak te linken aan de moeder/foetus/kind. (Bv. doodsoorzaak kind lag aan een aandoening van de moeder.) Dit veld ontbreekt in Doodsoorzaak. Hoe kunnen we dit modelleren?

**Comment by jitsedc** [comment]
- duur werd toegevoegd. Periode is echter aangewezen om gebruikt te worden. Hierbij is het echter niet nodig om een begin- of einddatum te geven. De twee waarden binnen een Periode kunnen uren zijn die van elkaar kunnen afgetrokken worden om de duur in uren te krijgen.
- Kardinaliteit van Doodsoorzaak.volgtOp werd op 0..1 gezet.
- Geassocieerde Oorzaak is een specialisatie gemaakt van Doodsoorzaak waarbij er kan overgeërfd worden voor attribuering en associaties. Het attribuut van Doodsoorzaak.doodsoorzaak werd gewijzigd naar 'beschrijving' met als verwachte waarde TaalString.
- Er werd een nieuw attribuut toegevoegd: Doodsoorzaak.gelinktAan:Gezondheidstoestand waarmee kan verwezen worden naar een Gezondheidstoestand van een andere Persoon.

**Comment by tdekeyser** [comment]
Volgens mij zit er conceptueel nog iets niet goed tussen de doodsoorzaken en geassocieerde oorzaken. In het formulier zijn geassocieerde oorzaken (sectie II) ziekten die bijgedragen hebben tot de dood, maar niet in verband staan met de logische samenhang van doodsoorzaken (sectie I).

<img width="1419" alt="image" src="https://github.com/Informatievlaanderen/OSLOthema-overlijdensaangifte/assets/12743692/a279c599-524d-425f-b329-ba05e6b2bbfd">

Is het haalbaar om dit als twee verschillende velden te modelleren (`doodsoorzaken` en `geassocieerdeOorzaken`), waarbij je sectie I modelleert als een linked list van Doodsoorzaak (via volgtOp), en sectie II als een lijst van Doodsoorzaken? Zo hoeft er eigenlijk geen inheritance gebruikt te worden.

Het gelinktAan veld is een mogelijke oplossing, maar dan moet dit wel op Doodsoorzaak staan, aangezien daarvoor ook moet kunnen aangeduid worden wie gelinkt is. Gelinkt aan een Gezondheidstoestand lijkt me daarentegen problematischer: de doodsoorzaak zelf is reeds een soort medische toestand. Ook willen we niet te veel hops introduceren tot de Persoon.

**Comment by jitsedc** [comment]
![image](https://github.com/Informatievlaanderen/OSLOthema-overlijdensaangifte/assets/93584054/811aef5c-6e7d-49ee-8955-4e22cbb64e85)

Dag Tom, heb ik het zo juist begrepen? De link met Gezondheidstoestand was voor mij wat toekomstgericht denken maar via Overlijdenstoestand>doodsoorzaak heb jij eigenlijk ook al de link. Indien oké zo pas ik het aan. Anders hoor ik graag je feedback.

Eventueel kunnen we er nog een codelijst aan koppelen maar dacht dit expliciet dan de vraag was om niet te doen.

**Comment by tdekeyser** [comment]
We hebben hier wel een codelijst aan gekoppeld, dus: `gelinktAan: DoodsoorzaakGelinktAan [0..1]`. En hierin zit dan `[Moeder, Kind, Foetus]`. Dit leek ons het makkelijkste om zo weinig mogelijk hops te moeten maken. (We hebben momenteel het "gerelateerdAan" genoemd, maar dat is hetzelfde.)

**Comment by jitsedc** [comment]
Heb je liever dat we dan gerelateerdAan:Persoon gebruiken? Dan kan je altijd nog vertakken naar de moeder, kind of foetus via de persoonsrelaties?

**Comment by jitsedc** [comment]
gerelateerd aan gebruikt in laatste publicatie.
