### ISSUE TITLE
MedischVerslagOverlijden.datum

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#7]
Veld “datum” ontbreekt om het tijdstip van de vaststelling overlijden aan te geven. De vaststelling moet een datum hebben wanneer het “ingediend” is.

**Comment by jitsedc** [comment]
datum werd toegevoegd als attribuut voor Bewijs.

**Comment by tdekeyser** [comment]
in orde - mag gesloten worden
