### ISSUE TITLE
Persoon.persoonsgebeurtenis

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#8]
Periode/ datum past hier niet in
Je hebt:

- Een datetime nodig voor de meeste
- Je hebt voor een tijd overlijden potentieel een vager begrip nodig

**Comment by jitsedc** [comment]
tijdspanne werd toegevoegd als alternatief attribuut met usageNote dat dit enkel in edge cases te gebruiken is.

**Comment by tdekeyser** [comment]
in orde, mag gesloten worden
