### ISSUE TITLE
MedischVerslag.status

### ISSUE THREAD

**Issue by jitsedc** [Informatievlaanderen/OSLOthema-overlijdensaangifte#9]
MedischVerslag refereert naar FHIR DiagnosticReport. FHIR DiagnosticReport gebruikt een DiagnosticReportStatus codelijst. We moeten die vertalen en integreren in het OSLO model.

**Comment by jitsedc** [comment]
MedischVerslag.status werd toegevoegd gemapt op de FHIR URI met een verwachte codelijst (op het UML diagram is er een suggestie gedaan voor de vertalingen van de waarden).

**Comment by tdekeyser** [comment]
In orde. Mag gesloten worden
